ALTER TABLE ACCOUNTED_DATA
ADD FOREIGN KEY (UserID) 
REFERENCES USERS_DATA(ID);

ALTER TABLE PERMISSION_SDATA 
ADD FOREIGN KEY (ID) 
REFERENCES USERS_DATA(ID);

ALTER TABLE ACCOUNTED_DATA 
ADD FOREIGN KEY (UserID) 
REFERENCES PERMISSION_SDATA(ID);

CREATE INDEX PERMISSION_SDATA_ID_SUBRESOURCE ON PERMISSION_SDATA(id, Subresource);
